name: mlsystem
channels:
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
    - mlflow==2.19.0
    - scikit-learn==1.5.2   
    - pandas
    - numpy
    - matplotlib 
    - seaborn
    - joblib
    - yellowbrick
    - dagshub
    - python-dotenv
